const toast = document.querySelector('.toast');
let toastTimer;
const state = { cart: JSON.parse(localStorage.getItem('rimsn_cart') || '[]'), mode: 'login' };
const money = value => `$${Number(value).toFixed(2)}`;
function showToast(message) { if (!toast) return; toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2800); }
function persistCart() { localStorage.setItem('rimsn_cart', JSON.stringify(state.cart)); updateCartCount(); }
function updateCartCount() { const count = document.querySelector('.cart-count'); if (!count) return; count.textContent = state.cart.reduce((sum, item) => sum + item.quantity, 0); count.style.display = state.cart.length ? 'flex' : 'none'; }
function injectStoreStyles() { const style = document.createElement('style'); style.textContent = `.store-drawer{position:fixed;inset:0;z-index:30;display:none;background:#03050ccc;backdrop-filter:blur(10px)}.store-drawer.open{display:block}.drawer-panel{position:absolute;top:0;bottom:0;left:0;width:min(440px,100%);padding:28px;background:#111625;border-right:1px solid var(--line);box-shadow:20px 0 80px #0008;overflow:auto}.drawer-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:18px}.drawer-head h2{font-size:24px;margin:0}.drawer-close{border:0;background:none;color:var(--muted);font-size:28px}.cart-empty{color:var(--muted);text-align:center;padding:70px 10px}.cart-line{display:grid;grid-template-columns:58px 1fr auto;gap:12px;align-items:center;padding:16px 0;border-bottom:1px solid var(--line)}.cart-thumb{height:58px;border-radius:10px}.cart-line h3{font-size:13px;margin:0}.cart-line small{color:var(--muted)}.cart-line strong{font:600 14px 'Space Grotesk'}.qty-controls{display:flex;gap:8px;align-items:center;margin-top:6px}.qty-controls button{width:22px;height:22px;border:1px solid var(--line);border-radius:6px;background:transparent;color:var(--text)}.cart-total{display:flex;justify-content:space-between;margin:24px 0;font-size:18px}.checkout-button{width:100%}.product-card{cursor:pointer}.product-card .add-cart{cursor:pointer;position:relative;z-index:1}.checkout-modal{position:fixed;inset:0;z-index:40;display:none;place-items:center;padding:20px;background:#03050ccc;backdrop-filter:blur(12px)}.checkout-modal.open{display:grid}.checkout-box{width:min(100%,460px);background:#111625;border:1px solid var(--line);border-radius:22px;padding:28px}.checkout-box h2{margin-top:0}.checkout-box input{display:block;width:100%;margin:7px 0 14px;padding:12px;border-radius:9px;border:1px solid var(--line);background:#0b0f1c;color:var(--text)}.checkout-box .button{width:100%;margin-top:8px}.search-input{width:min(270px,100%);padding:10px 14px;border:1px solid var(--line);border-radius:10px;background:#ffffff08;color:var(--text);outline:0;font:inherit;font-size:12px}.search-input:focus{border-color:var(--cyan)}@media(max-width:800px){.search-input{display:none}}`; document.head.appendChild(style); }
function buildCart() { const wrapper = document.createElement('div'); wrapper.className = 'store-drawer'; wrapper.id = 'storeDrawer'; wrapper.innerHTML = `<aside class="drawer-panel" role="dialog" aria-modal="true" aria-labelledby="cartTitle"><div class="drawer-head"><h2 id="cartTitle">سلة المنتجات</h2><button class="drawer-close" aria-label="إغلاق">×</button></div><div class="cart-items"></div><div class="cart-summary"><div class="cart-total"><span>الإجمالي</span><strong>$0.00</strong></div><button class="button button-primary checkout-button">إتمام الطلب <span>↗</span></button></div></aside>`; document.body.appendChild(wrapper); wrapper.addEventListener('click', event => { if (event.target === wrapper || event.target.closest('.drawer-close')) closeCart(); }); wrapper.querySelector('.checkout-button').addEventListener('click', openCheckout); }
function renderCart() { const drawer = document.querySelector('#storeDrawer'); if (!drawer) return; const target = drawer.querySelector('.cart-items'); const summary = drawer.querySelector('.cart-total strong'); if (!state.cart.length) { target.innerHTML = '<p class="cart-empty">سلتك جاهزة لاستقبال أول منتج لك ✦</p>'; summary.textContent = '$0.00'; drawer.querySelector('.checkout-button').disabled = true; return; } drawer.querySelector('.checkout-button').disabled = false; target.innerHTML = state.cart.map(item => `<div class="cart-line"><div class="cart-thumb ${item.art}"></div><div><h3>${item.name}</h3><small>${money(item.price)}</small><div class="qty-controls"><button data-action="minus" data-id="${item.id}">−</button><span>${item.quantity}</span><button data-action="plus" data-id="${item.id}">+</button><button data-action="remove" data-id="${item.id}" title="حذف">×</button></div></div><strong>${money(item.price * item.quantity)}</strong></div>`).join(''); const total = state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0); summary.textContent = money(total); target.querySelectorAll('button').forEach(button => button.addEventListener('click', () => { const item = state.cart.find(x => x.id === button.dataset.id); if (button.dataset.action === 'remove') state.cart = state.cart.filter(x => x.id !== button.dataset.id); else if (item) item.quantity += button.dataset.action === 'plus' ? 1 : -1; state.cart = state.cart.filter(x => x.quantity > 0); persistCart(); renderCart(); })); }
function openCart() { renderCart(); document.querySelector('#storeDrawer').classList.add('open'); }
function closeCart() { document.querySelector('#storeDrawer')?.classList.remove('open'); }
function addToCart(button) { const card = button.closest('.product-card'); if (!card) return; const name = card.querySelector('h3')?.textContent || 'منتج رقمي'; const price = Number((card.querySelector('.product-info strong')?.textContent || '$0').replace(/[^0-9.]/g, '')); const id = name.toLowerCase().replace(/\s+/g, '-'); const art = [...card.querySelector('.product-art').classList].find(x => x.startsWith('art-')) || 'art-one'; const item = state.cart.find(x => x.id === id); if (item) item.quantity += 1; else state.cart.push({ id, name, price, art, quantity: 1 }); persistCart(); button.textContent = 'تمت الإضافة ✓'; button.style.color = 'var(--cyan)'; showToast('تمت إضافة المنتج إلى سلتك'); }
function openCheckout() { if (!state.cart.length) return; const modal = document.createElement('div'); modal.className = 'checkout-modal open'; modal.innerHTML = `<section class="checkout-box" role="dialog" aria-modal="true"><button class="modal-close" aria-label="إغلاق">×</button><p class="kicker">دفع آمن</p><h2>أكمل طلبك</h2><p style="color:var(--muted);font-size:13px">هذه معاينة لرحلة الدفع. اربط Stripe أو Moyasar قبل الإطلاق.</p><label>البريد الإلكتروني<input type="email" required placeholder="you@example.com"></label><label>الاسم على الفاتورة<input type="text" required placeholder="اسمك الكامل"></label><button class="button button-primary" type="button">متابعة للدفع <span>↗</span></button></section>`; document.body.appendChild(modal); const close = () => modal.remove(); modal.addEventListener('click', e => { if (e.target === modal || e.target.closest('.modal-close')) close(); }); modal.querySelector('.button').addEventListener('click', () => { showToast('واجهة الدفع جاهزة للربط بمزود الدفع'); close(); }); }

document.addEventListener('DOMContentLoaded', () => { injectStoreStyles(); buildCart(); updateCartCount(); document.querySelectorAll('.pill').forEach(pill => pill.addEventListener('click', () => { document.querySelectorAll('.pill').forEach(x => x.classList.remove('active')); pill.classList.add('active'); const filter = pill.dataset.filter; document.querySelectorAll('.product-card').forEach(card => card.classList.toggle('hidden', filter !== 'all' && card.dataset.category !== filter)); })); document.querySelectorAll('.add-cart').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); addToCart(button); })); document.querySelector('.cart-button')?.addEventListener('click', openCart); document.querySelectorAll('.product-card').forEach(card => card.addEventListener('click', () => showToast('اضغط «أضف للسلة» لشراء هذا المنتج'))); const heading = document.querySelector('.section-heading'); if (heading && !heading.querySelector('.search-input')) { const search = document.createElement('input'); search.className = 'search-input'; search.placeholder = 'ابحث عن منتج...'; search.setAttribute('aria-label', 'البحث عن منتج'); heading.appendChild(search); search.addEventListener('input', () => { const query = search.value.trim().toLowerCase(); document.querySelectorAll('.product-card').forEach(card => card.classList.toggle('hidden', query && !card.textContent.toLowerCase().includes(query))); }); } });

const modal = document.querySelector('#authModal'); const form = document.querySelector('#authForm'); const title = document.querySelector('#authTitle'); const subtitle = document.querySelector('#authSubtitle'); const nameField = document.querySelector('#nameField'); const submit = form?.querySelector('.submit-auth'); const success = document.querySelector('#authSuccess');
function setMode(mode) { state.mode = mode; document.querySelectorAll('[data-mode]').forEach(x => x.classList.toggle('selected', x.dataset.mode === mode)); const signup = mode === 'signup'; if (nameField) { nameField.style.display = signup ? 'block' : 'none'; nameField.querySelector('input').required = signup; } if (title) title.textContent = signup ? 'اصنع حسابك.' : 'أهلاً بعودتك.'; if (subtitle) subtitle.textContent = signup ? 'ابدأ ببناء مستقبلك الرقمي.' : 'سجّل الدخول لتكمل رحلتك.'; if (submit) submit.innerHTML = signup ? 'إنشاء الحساب <span>↗</span>' : 'تسجيل الدخول <span>↗</span>'; }
function openAuth(mode = 'login') { modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); setMode(mode); setTimeout(() => form.email.focus(), 50); }
function closeAuth() { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); form.reset(); success.hidden = true; form.hidden = false; document.querySelector('.forgot-link').hidden = false; }
document.querySelectorAll('[data-auth]').forEach(button => button.addEventListener('click', event => { event.preventDefault(); openAuth(button.dataset.auth); })); document.querySelectorAll('[data-mode]').forEach(button => button.addEventListener('click', () => setMode(button.dataset.mode))); document.querySelector('.modal-close')?.addEventListener('click', closeAuth); modal?.addEventListener('click', event => { if (event.target === modal) closeAuth(); }); document.addEventListener('keydown', event => { if (event.key === 'Escape') { closeAuth(); closeCart(); } });
form?.addEventListener('submit', event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const users = JSON.parse(localStorage.getItem('rimsn_users') || '[]'); if (state.mode === 'signup') { if (users.some(user => user.email === data.email)) return showToast('هذا البريد مسجل بالفعل'); users.push({ name: data.name, email: data.email, password: data.password }); localStorage.setItem('rimsn_users', JSON.stringify(users)); localStorage.setItem('rimsn_session', JSON.stringify({ name: data.name, email: data.email })); showSuccess(`مرحباً ${data.name} — تم إنشاء حسابك بنجاح.`); } else { const user = users.find(item => item.email === data.email && item.password === data.password); if (!user) return showToast('البريد الإلكتروني أو كلمة المرور غير صحيحة'); localStorage.setItem('rimsn_session', JSON.stringify({ name: user.name, email: user.email })); showSuccess(`مرحباً بعودتك ${user.name}.`); } });
function showSuccess(message) { form.hidden = true; document.querySelector('.forgot-link').hidden = true; success.textContent = message; success.hidden = false; setTimeout(closeAuth, 2200); }
document.querySelector('#forgotPassword')?.addEventListener('click', () => { const email = window.prompt('أدخل بريدك الإلكتروني لاستعادة كلمة المرور:'); if (email?.includes('@')) showToast('تم إرسال رابط الاستعادة إلى بريدك (وضع المعاينة)'); else if (email) showToast('يرجى إدخال بريد إلكتروني صحيح'); }); document.querySelector('#languageButton')?.addEventListener('click', () => showToast('تجربة English ستتوفر قريباً')); document.querySelector('.menu-button')?.addEventListener('click', () => showToast('استخدم الروابط للتنقل في النسخة المتجاوبة')); const existing = JSON.parse(localStorage.getItem('rimsn_session') || 'null'); if (existing) { const loginButton = document.querySelector('[data-auth="login"]'); if (loginButton) { loginButton.textContent = `مرحباً، ${existing.name.split(' ')[0]}`; loginButton.addEventListener('click', () => { localStorage.removeItem('rimsn_session'); location.reload(); }); } }
