import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, ChevronDown, CircleHelp, ExternalLink, FileText, Heart, LogIn, LogOut, MessageCircle, MousePointer2, RefreshCw, Search, ShieldCheck, Sparkles, Trash2, Twitter, UserRound, X } from "lucide-react";
import { toast } from "sonner";

type Post = { id: string; text: string; createdAt?: string; isReply: boolean };
type Scan = { user: { id: string; name: string; username: string; profile_image_url?: string }; posts: Post[]; likedPosts: Post[]; counts: { posts: number; replies: number; likes: number } };

const api = async <T,>(url: string, init?: RequestInit) => { const response = await fetch(url, { credentials: "include", ...init }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || data.message || "تعذر إكمال العملية"); return data as T; };

function Brand() { return <div className="clean-brand"><div className="clean-mark"><Sparkles size={17} /></div><div><b>ممحاة</b><span>X CLEANER</span></div></div>; }
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number | string }) { return <div className="clean-stat"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></div>; }

export default function Home() {
  const [status, setStatus] = useState<{ configured: boolean; connected: boolean }>({ configured: false, connected: false });
  const [scan, setScan] = useState<Scan | null>(null);
  const [selected, setSelected] = useState<string[]>([]);
  const [filter, setFilter] = useState<"all" | "replies" | "likes">("all");
  const [search, setSearch] = useState("");
  const [limit, setLimit] = useState(100);
  const [busy, setBusy] = useState(false);
  const [showDelete, setShowDelete] = useState(false);
  const [confirmText, setConfirmText] = useState("");

  const loadStatus = () => api<{ configured: boolean; connected: boolean }>("/api/x/status").then(setStatus).catch(() => undefined);
  useEffect(() => { loadStatus(); }, []);
  const visible = useMemo(() => (filter === "likes" ? (scan?.likedPosts ?? []) : (scan?.posts ?? []).filter((post) => filter === "all" || post.isReply)).filter((post) => post.text.toLowerCase().includes(search.toLowerCase())).slice(0, limit), [filter, limit, scan, search]);

  const connect = () => { window.location.href = "/api/x/login"; };
  const scanAccount = async () => { setBusy(true); try { const data = await api<Scan>("/api/x/scan"); setScan(data); setSelected([]); toast.success(`تم العثور على ${data.counts.posts} منشور`); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر الفحص"); } finally { setBusy(false); } };
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const selectVisible = () => setSelected((current) => current.length === visible.length ? [] : visible.map((post) => post.id));
  const deleteSelected = async () => { if (confirmText !== "حذف") return; setBusy(true); try { const endpoint = filter === "likes" ? "/api/x/unlike" : "/api/x/delete"; const result = await api<{ deleted: number; failed: number }>(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ids: selected }) }); toast.success(filter === "likes" ? `تمت إزالة ${result.deleted} إعجاب` : `تم حذف ${result.deleted} منشور${result.failed ? `، وفشل ${result.failed}` : ""}`); setShowDelete(false); setConfirmText(""); await scanAccount(); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر تنفيذ العملية"); } finally { setBusy(false); } };

  return <div className="clean-app" dir="rtl">
    <header className="clean-header"><Brand /><nav><a className="active">لوحة التحكم</a><a>سجل العمليات</a><a>المساعدة <CircleHelp size={14} /></a></nav><div className="clean-account">{scan?.user ? <><img src={scan.user.profile_image_url} /><span>@{scan.user.username}</span><button onClick={() => api("/api/x/disconnect", { method: "POST" }).then(() => { setStatus({ configured: status.configured, connected: false }); setScan(null); })}><LogOut size={15} /></button></> : <span className="secure-mini"><ShieldCheck size={14} /> لا نحفظ كلمة المرور</span>}</div></header>
    <main className="clean-shell">
      <div className="clean-hero"><div><div className="clean-overline"><span /> أداة تنظيف حسابك</div><h1>نظّف حساب X<br /><em>بهدوء، وبنقرة واعية.</em></h1><p>اعرض منشوراتك وردودك أولًا، حدد ما تريد، ثم نفّذ الحذف وأنت ترى بالضبط ما سيحدث.</p></div><div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><Twitter size={42} /></div></div>
      {!status.connected ? <section className="connect-card"><div className="connect-icon"><LogIn size={23} /></div><div className="connect-copy"><h2>اربط حساب X للبدء</h2><p>ستنتقل إلى X لتسجيل الدخول والموافقة على الصلاحيات. لن نرى كلمة المرور، ويمكنك فصل الحساب في أي وقت.</p><div className="scope-row"><span><ShieldCheck size={13} /> OAuth آمن</span><span><FileText size={13} /> معاينة قبل الحذف</span><span><MousePointer2 size={13} /> تحكم كامل</span></div></div><button className="clean-primary" onClick={connect} disabled={!status.configured}><span>{status.configured ? "تسجيل الدخول عبر X" : "إعداد X OAuth مطلوب"}</span>{status.configured ? <ExternalLink size={16} /> : <AlertTriangle size={16} />}</button>{!status.configured && <small className="setup-hint">أضف X_CLIENT_ID و X_REDIRECT_URI في Secrets أولًا.</small>}</section> : <>
        <section className="clean-toolbar"><div className="user-summary"><div className="user-avatar">{scan?.user ? <img src={scan.user.profile_image_url} /> : <UserRound size={19} />}</div><div><b>{scan?.user ? scan.user.name : "حساب X متصل"}</b><small>{scan?.user ? `@${scan.user.username}` : "اضغط فحص الحساب لقراءة المنشورات"}</small></div></div><div className="toolbar-actions"><button className="clean-secondary" onClick={scanAccount} disabled={busy}><RefreshCw size={15} className={busy ? "spin" : ""} /> فحص الحساب</button><button className="clean-secondary danger-text" onClick={() => api("/api/x/disconnect", { method: "POST" }).then(() => { setStatus({ configured: status.configured, connected: false }); setScan(null); })}><LogOut size={15} /> فصل الحساب</button></div></section>
        <section className="stats-grid"><Stat icon={<FileText size={17} />} label="كل المنشورات" value={scan?.counts.posts ?? "—"} /><Stat icon={<MessageCircle size={17} />} label="الردود" value={scan?.counts.replies ?? "—"} /><Stat icon={<Heart size={17} />} label="الإعجابات" value={scan?.counts.likes ?? "—"} /><div className="privacy-note"><ShieldCheck size={19} /><span><b>خصوصيتك أولًا</b><small>التوكن مشفّر ولا نعرضه للمتصفح</small></span></div></section>
        <section className="posts-card"><div className="posts-head"><div><h2>{filter === "likes" ? "إعجاباتك" : "منشوراتك"}</h2><span>{selected.length ? `تم تحديد ${selected.length}` : filter === "likes" ? "حدد الإعجابات التي تريد إزالتها" : "حدد العناصر التي تريد حذفها"}</span></div><div className="posts-controls"><div className="clean-search"><Search size={14} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث في النص..." /></div><select value={filter} onChange={(event) => { setFilter(event.target.value as "all" | "replies" | "likes"); setSelected([]); }}><option value="all">كل المنشورات</option><option value="replies">الردود فقط</option><option value="likes">الإعجابات</option></select><select value={limit} onChange={(event) => setLimit(Number(event.target.value))}><option value={10}>أول 10</option><option value={100}>أول 100</option><option value={1000}>أول 1000</option></select></div></div><div className="select-all"><label><input type="checkbox" checked={visible.length > 0 && selected.length === visible.length} onChange={selectVisible} /><span>تحديد الظاهر</span></label><small>{visible.length} نتيجة</small></div><div className="post-list">{!scan ? <div className="empty-clean"><RefreshCw size={22} /><p>اضغط «فحص الحساب» لعرض منشوراتك هنا</p></div> : visible.length === 0 ? <div className="empty-clean"><Search size={22} /><p>لم نجد منشورات تطابق البحث</p></div> : visible.map((post) => <label className={`post-row ${selected.includes(post.id) ? "picked" : ""}`} key={post.id}><input type="checkbox" checked={selected.includes(post.id)} onChange={() => toggle(post.id)} /><div className="post-content"><p>{post.text}</p><small>{filter === "likes" ? "إعجاب" : post.isReply ? "رد" : "منشور"} · {post.createdAt ? new Date(post.createdAt).toLocaleDateString("ar") : ""}</small></div><span className="post-id">#{post.id.slice(-6)}</span></label>)}</div>{selected.length > 0 && <div className="bulk-bar"><span><Check size={16} /> {selected.length} {filter === "likes" ? "إعجاب محدد" : "منشور محدد"}</span><button className="delete-btn" onClick={() => setShowDelete(true)}><Trash2 size={15} /> {filter === "likes" ? "إزالة الإعجاب" : "حذف المحدد"}</button></div>}</section>
      </>}
      <footer className="clean-footer"><span>ممحاة X © 2026</span><span>الحذف نهائي وقد يستغرق وقتًا حسب حدود X API</span><span><ShieldCheck size={13} /> لا نبيع بياناتك</span></footer>
    </main>
    {showDelete && <div className="modal-backdrop"><div className="delete-modal"><div className="modal-alert"><AlertTriangle size={23} /></div><h2>{filter === "likes" ? "تأكيد إزالة الإعجاب" : "تأكيد الحذف النهائي"}</h2><p>أنت على وشك {filter === "likes" ? "إزالة" : "حذف"} <b>{selected.length} {filter === "likes" ? "إعجاب" : "منشور"}</b> من حساب X. هذا الإجراء قد لا يمكن التراجع عنه.</p><div className="modal-warning">للتأكيد، اكتب كلمة <b>حذف</b> في الحقل أدناه.</div><input autoFocus value={confirmText} onChange={(event) => setConfirmText(event.target.value)} placeholder="اكتب: حذف" /><div className="modal-actions"><button className="clean-secondary" onClick={() => { setShowDelete(false); setConfirmText(""); }}>إلغاء</button><button className="delete-btn" disabled={confirmText !== "حذف" || busy} onClick={deleteSelected}><Trash2 size={15} /> تأكيد العملية</button></div></div></div>}
  </div>;
}
