import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { FormEvent, ReactNode, useEffect, useState } from 'react';

type User = { id: string; name: string; email: string; role: 'admin' | 'customer' };
type Product = { _id: string; title: string; category: string; price: number; originalPrice?: number; imageUrl: string; description: string; shortDescription?: string; tags?: string[]; features?: string[]; badge?: string; format?: string; fileSize?: string; level?: string; fileUrl?: string; active?: boolean };
type CartItem = { id: string; qty: number };

const api = async <T,>(path: string, options: RequestInit = {}) => {
  const token = localStorage.getItem('rimsn_token');
  const headers = new Headers(options.headers || {});
  headers.set('Content-Type', 'application/json');
  if (token) headers.set('Authorization', 'Bearer ' + token);

  const response = await fetch('/api' + path, {
    ...options,
    headers,
  });

  const rawText = await response.text();
  let body: any = null;
  if (rawText) {
    try {
      body = JSON.parse(rawText);
    } catch {
      body = { message: rawText };
    }
  }

  if (!response.ok) {
    throw new Error((body && (body.message || body.error)) || 'حدث خطأ غير متوقع');
  }

  return body as T;
};
const price = (value: number) => new Intl.NumberFormat('ar-SA', { style: 'currency', currency: 'SAR', maximumFractionDigits: 0 }).format(value);
const cartRead = (): CartItem[] => JSON.parse(localStorage.getItem('rimsn_cart') || '[]');
const cartWrite = (items: CartItem[]) => { localStorage.setItem('rimsn_cart', JSON.stringify(items)); window.dispatchEvent(new Event('rimsn-cart')); };

function App() {
  const [user, setUser] = useState<User | null>(() => JSON.parse(localStorage.getItem('rimsn_user') || 'null'));
  const [cartCount, setCartCount] = useState(() => cartRead().reduce((sum, item) => sum + item.qty, 0));
  useEffect(() => { const update = () => setCartCount(cartRead().reduce((sum, item) => sum + item.qty, 0)); window.addEventListener('rimsn-cart', update); return () => window.removeEventListener('rimsn-cart', update); }, []);
  const logout = () => { localStorage.removeItem('rimsn_token'); localStorage.removeItem('rimsn_user'); setUser(null); };
  return <BrowserRouter><div className="site-shell"><header className="topbar glass-panel"><Link to="/" className="brand-mark">ط±ظگظ…ظ’ط³ظژظ†</Link><nav className="nav-menu"><NavLink to="/" end className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>ط§ظ„ط±ط¦ظٹط³ظٹط©</NavLink><NavLink to="/products" className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>ط§ظ„ظ…ظ†طھط¬ط§طھ</NavLink>{user ? <NavLink to="/dashboard" className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>ظ…ط´طھط±ظٹط§طھظٹ</NavLink> : null}{user?.role === 'admin' ? <NavLink to="/admin" className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}>ط§ظ„ط¥ط¯ط§ط±ط©</NavLink> : null}</nav><div className="topbar-actions">{user ? <button className="ghost-btn small-btn" onClick={logout}>ط®ط±ظˆط¬</button> : <Link to="/auth" className="ghost-btn small-btn">طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„</Link>}<Link to="/cart" className="cart-pill">ط§ظ„ط³ظ„ط© <strong>{cartCount}</strong></Link></div></header><main className="page-wrap"><Routes><Route path="/" element={<Home />} /><Route path="/products" element={<Products />} /><Route path="/product/:id" element={<ProductDetail />} /><Route path="/cart" element={<Cart user={user} />} /><Route path="/checkout" element={<Checkout user={user} />} /><Route path="/auth" element={<Auth onLogin={setUser} />} /><Route path="/dashboard" element={<Dashboard user={user} />} /><Route path="/admin" element={<Admin user={user} />} /></Routes></main><footer className="footer glass-panel"><strong>ط±ظگظ…ظ’ط³ظژظ†</strong><p>ظ…ظ†طھط¬ط§طھ ط±ظ‚ظ…ظٹط© ط¹ط±ط¨ظٹط©طŒ ط´ط±ط§ط، ط¢ظ…ظ† ظˆطھظ†ط²ظٹظ„ ظ…ط­ظ…ظٹ.</p></footer></div></BrowserRouter>;
}

function useProducts() {
  const [products, setProducts] = useState<Product[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); api<Product[]>('/products').then(setProducts).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(load, []); return { products, loading, error, reload: load };
}
function Home() { const data = useProducts(); return <><section className="hero glass-panel"><div className="hero-copy"><span className="eyebrow">ظ…طھط¬ط± ط±ظ‚ظ…ظٹ ط¹ط±ط¨ظٹ</span><h1>ظ…ظ†طھط¬ط§طھ ط±ظ‚ظ…ظٹط© ظ…ظˆط«ظˆظ‚ط© ظ„ظ…ط´ط±ظˆط¹ظƒ.</h1><p>ط§ط´طھط±ظگ ظ…ظ†طھط¬ظƒطŒ ط§ط¯ظپط¹طŒ ط«ظ… ط­ظ…ظ‘ظ„ ظ…ظ„ظپط§طھظƒ ظ…ظ† ط­ط³ط§ط¨ظƒ ط¨ط£ظ…ط§ظ†.</p><div className="hero-actions"><Link className="btn primary" to="/products">طھطµظپط­ ط§ظ„ظ…ظ†طھط¬ط§طھ</Link><Link className="btn secondary" to="/auth">ط¥ظ†ط´ط§ط، ط­ط³ط§ط¨</Link></div></div><div className="hero-visual"><div className="hero-card glass-panel"><div className="chart-box"><div className="chart-bar" style={{ height: '35%' }} /><div className="chart-bar" style={{ height: '58%' }} /><div className="chart-bar" style={{ height: '80%' }} /><div className="chart-bar" style={{ height: '98%' }} /></div><div className="sale-pill">طھظ†ط²ظٹظ„ ظ…ط­ظ…ظٹ ط¨ط¹ط¯ ط§ظ„ط´ط±ط§ط،</div></div></div></section><section className="section-block"><div className="section-heading"><div><span className="eyebrow">ط§ظ„ظ…ظ†طھط¬ط§طھ</span><h2>ط£ط­ط¯ط« ط§ظ„ظ…ظ†طھط¬ط§طھ</h2></div><Link to="/products" className="inline-link">ط¹ط±ط¶ ط§ظ„ظƒظ„</Link></div><ProductGrid products={data.products.slice(0, 3)} loading={data.loading} error={data.error} reload={data.reload} /></section></>; }
function Products() { const data = useProducts(); const [query, setQuery] = useState(''); const [category, setCategory] = useState('ط§ظ„ظƒظ„'); const categories = ['ط§ظ„ظƒظ„', ...new Set(data.products.map((p) => p.category))]; const products = data.products.filter((p) => (category === 'ط§ظ„ظƒظ„' || p.category === category) && (!query || `${p.title} ${p.category} ${(p.tags || []).join(' ')}`.toLowerCase().includes(query.toLowerCase()))); return <section className="section-block"><div className="section-heading"><div><span className="eyebrow">ط§ظ„ظ…ظƒطھط¨ط©</span><h2>ط§ظ„ظ…ظ†طھط¬ط§طھ ط§ظ„ط±ظ‚ظ…ظٹط©</h2></div></div><div className="toolbar glass-panel"><input placeholder="ط§ط¨ط­ط« ط¹ظ† ظ…ظ†طھط¬..." value={query} onChange={(e) => setQuery(e.target.value)} /><select value={category} onChange={(e) => setCategory(e.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></div><ProductGrid products={products} loading={data.loading} error={data.error} reload={data.reload} /></section>; }
function ProductGrid({ products, loading, error, reload }: { products: Product[]; loading: boolean; error: string; reload: () => void }) { if (loading) return <Loading />; if (error) return <Empty title="طھط¹ط°ط± طھط­ظ…ظٹظ„ ط§ظ„ظ…ظ†طھط¬ط§طھ" text={error} action={<button className="btn primary" onClick={reload}>ط¥ط¹ط§ط¯ط© ط§ظ„ظ…ط­ط§ظˆظ„ط©</button>} />; if (!products.length) return <Empty title="ظ„ط§ طھظˆط¬ط¯ ظ…ظ†طھط¬ط§طھ ظ…ظ†ط´ظˆط±ط©" text="ط£ط¶ظپ ظ…ظ†طھط¬ط§طھظƒ ظ…ظ† ظ„ظˆط­ط© ط§ظ„ط¥ط¯ط§ط±ط©." />; return <div className="product-grid">{products.map((p) => <ProductCard key={p._id} product={p} />)}</div>; }
function ProductCard({ product }: { product: Product }) { const add = () => { const items = cartRead(); const exists = items.find((i) => i.id === product._id); cartWrite(exists ? items.map((i) => i.id === product._id ? { ...i, qty: i.qty + 1 } : i) : [...items, { id: product._id, qty: 1 }]); }; return <article className="product-card glass-panel"><div className="product-image-wrap"><img className="product-image" src={product.imageUrl} alt={product.title} />{product.badge ? <span className="product-badge">{product.badge}</span> : null}</div><div className="product-info"><div className="product-meta"><span>{product.category}</span><span>ظ…ظ†طھط¬ ط±ظ‚ظ…ظٹ</span></div><h3>{product.title}</h3><p>{product.shortDescription || product.description}</p><div className="price-row"><strong>{price(product.price)}</strong><button className="btn primary small" onClick={add}>ط£ط¶ظپ ظ„ظ„ط³ظ„ط©</button></div><Link className="inline-link" to={`/product/${product._id}`}>ط¹ط±ط¶ ط§ظ„طھظپط§طµظٹظ„</Link></div></article>; }
function ProductDetail() { const { id } = useParams(); const { products, loading } = useProducts(); const product = products.find((p) => p._id === id); if (loading) return <Loading />; if (!product) return <Empty title="ط§ظ„ظ…ظ†طھط¬ ط؛ظٹط± ظ…ظˆط¬ظˆط¯" text="طھط­ظ‚ظ‚ ظ…ظ† ط§ظ„ط±ط§ط¨ط· ط£ظˆ ط£ط¶ظپ ط§ظ„ظ…ظ†طھط¬ ظ…ظ† ط§ظ„ط¥ط¯ط§ط±ط©." />; return <section className="section-block product-detail"><div className="product-detail-grid"><div className="glass-panel detail-visual"><img src={product.imageUrl} alt={product.title} /></div><div className="detail-copy"><span className="eyebrow">{product.category}</span><h1>{product.title}</h1><p>{product.description}</p><ul className="feature-list">{(product.features || []).map((f) => <li key={f}>{f}</li>)}</ul><div className="price-panel"><strong>{price(product.price)}</strong><span className="level-badge">{product.level || 'ط±ظ‚ظ…ظٹ'}</span></div><button className="btn primary" onClick={() => { cartWrite([...cartRead(), { id: product._id, qty: 1 }]); }}>ط£ط¶ظپ ط¥ظ„ظ‰ ط§ظ„ط³ظ„ط©</button></div></div></section>; }
function Cart({ user }: { user: User | null }) { const [items, setItems] = useState(cartRead); const { products, loading } = useProducts(); const update = (next: CartItem[]) => { setItems(next); cartWrite(next); }; const rows = items.map((item) => ({ ...item, product: products.find((p) => p._id === item.id) })).filter((row) => row.product); const total = rows.reduce((s, r) => s + (r.product?.price || 0) * r.qty, 0); if (loading) return <Loading />; if (!rows.length) return <Empty title="ط§ظ„ط³ظ„ط© ظپط§ط±ط؛ط©" text="ط£ط¶ظپ ظ…ظ†طھط¬ظ‹ط§ ظ„ظ„ظ…طھط§ط¨ط¹ط©." action={<Link className="btn primary" to="/products">طھطµظپط­ ط§ظ„ظ…ظ†طھط¬ط§طھ</Link>} />; return <section className="section-block checkout-shell"><div className="checkout-grid"><div className="glass-panel checkout-list">{rows.map((row) => <div className="cart-item-row" key={row.id}><img src={row.product?.imageUrl} alt={row.product?.title} /><div><h3>{row.product?.title}</h3><p>{row.product?.category}</p></div><div className="qty-box"><button onClick={() => update(items.map((i) => i.id === row.id ? { ...i, qty: i.qty - 1 } : i).filter((i) => i.qty > 0))}>-</button><span>{row.qty}</span><button onClick={() => update(items.map((i) => i.id === row.id ? { ...i, qty: i.qty + 1 } : i))}>+</button></div><strong>{price((row.product?.price || 0) * row.qty)}</strong></div>)}</div><aside className="glass-panel summary-panel"><h3>ط§ظ„ط¥ط¬ظ…ط§ظ„ظٹ</h3><div className="summary-row total-row"><span>ط§ظ„ظ…ط¬ظ…ظˆط¹</span><strong>{price(total)}</strong></div>{user ? <Link to="/checkout" className="btn primary block-btn">ظ…طھط§ط¨ط¹ط© ظ„ظ„ط¯ظپط¹</Link> : <Link to="/auth" className="btn primary block-btn">ط³ط¬ظ„ ط§ظ„ط¯ط®ظˆظ„ ظ„ظ„ط´ط±ط§ط،</Link>}</aside></div></section>; }
function Auth({ onLogin }: { onLogin: (user: User) => void }) { const [mode, setMode] = useState<'login' | 'register' | 'forgot'>('login'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [message, setMessage] = useState(''); const submit = async (e: FormEvent) => { e.preventDefault(); try { if (mode === 'forgot') { const data = await api<{ message: string }>('/auth/forgot', { method: 'POST', body: JSON.stringify({ email: form.email }) }); setMessage(data.message); return; } const data = await api<{ token: string; user: User }>(`/auth/${mode === 'register' ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(form) }); localStorage.setItem('rimsn_token', data.token); localStorage.setItem('rimsn_user', JSON.stringify(data.user)); onLogin(data.user); setMessage('طھظ… طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„ ط¨ظ†ط¬ط§ط­'); } catch (e) { setMessage((e as Error).message); } }; return <section className="auth-wrap section-block"><div className="glass-panel auth-card"><div className="auth-tabs">{(['login', 'register', 'forgot'] as const).map((item) => <button className={mode === item ? 'tab active' : 'tab'} key={item} onClick={() => setMode(item)}>{item === 'login' ? 'طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„' : item === 'register' ? 'ط¥ظ†ط´ط§ط، ط­ط³ط§ط¨' : 'ط§ط³طھط¹ط§ط¯ط© ظƒظ„ظ…ط© ط§ظ„ظ…ط±ظˆط±'}</button>)}</div><form className="auth-form" onSubmit={submit}>{mode === 'register' ? <label>ط§ظ„ط§ط³ظ…<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label> : null}<label>ط§ظ„ط¨ط±ظٹط¯<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label>{mode !== 'forgot' ? <label>ظƒظ„ظ…ط© ط§ظ„ظ…ط±ظˆط±<input required minLength={8} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label> : null}<button className="btn primary block-btn">{mode === 'login' ? 'ط¯ط®ظˆظ„' : mode === 'register' ? 'ط¥ظ†ط´ط§ط، ط§ظ„ط­ط³ط§ط¨' : 'ط¥ط±ط³ط§ظ„ ط±ط§ط¨ط· ط§ظ„ط§ط³طھط¹ط§ط¯ط©'}</button>{message ? <p>{message}</p> : null}</form></div></section>; }
function Checkout({ user }: { user: User | null }) { const navigate = useNavigate(); const { products, loading } = useProducts(); const items = cartRead(); const rows = items.map((item) => ({ ...item, product: products.find((p) => p._id === item.id) })).filter((r) => r.product); const total = rows.reduce((s, r) => s + (r.product?.price || 0) * r.qty, 0); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api('/orders', { method: 'POST', body: JSON.stringify({ items: rows.map((r) => ({ productId: r.id, quantity: r.qty })) }) }); cartWrite([]); navigate('/dashboard'); } catch (err) { alert((err as Error).message); } }; if (!user) return <AuthRequired />; if (loading) return <Loading />; return <section className="section-block checkout-shell"><div className="checkout-grid"><form className="glass-panel checkout-form" onSubmit={submit}><h2>ط¥طھظ…ط§ظ… ط§ظ„ط·ظ„ط¨</h2><p>ط§ظ„ط¯ظپط¹ ط§ظ„ط­ط§ظ„ظٹ طھط¬ط±ظٹط¨ظٹ. ط§ط±ط¨ط· Stripe ط£ظˆ Tap ظ‚ط¨ظ„ ط§ط³طھظ‚ط¨ط§ظ„ ط£ظ…ظˆط§ظ„ ط­ظ‚ظٹظ‚ظٹط©.</p><label>ط§ظ„ط§ط³ظ…<input required defaultValue={user.name} /></label><label>ط§ظ„ط¨ط±ظٹط¯<input required type="email" defaultValue={user.email} /></label><button className="btn primary block-btn">طھط£ظƒظٹط¯ ط§ظ„ط´ط±ط§ط، ط§ظ„طھط¬ط±ظٹط¨ظٹ</button></form><aside className="glass-panel summary-panel"><h3>ط§ظ„ط¥ط¬ظ…ط§ظ„ظٹ</h3><strong>{price(total)}</strong></aside></div></section>; }
function Dashboard({ user }: { user: User | null }) { const [orders, setOrders] = useState<Array<{ items: Array<{ productId: string; title: string; quantity: number }> }>>([]); const [error, setError] = useState(''); useEffect(() => { if (user) api<typeof orders>('/orders').then(setOrders).catch((e) => setError(e.message)); }, [user]); if (!user) return <AuthRequired />; const download = (id: string) => { const token = localStorage.getItem('rimsn_token'); window.open(`/api/download/${id}?token=${encodeURIComponent(token || '')}`, '_blank'); }; const items = orders.flatMap((o) => o.items); return <section className="section-block dashboard-shell"><div className="dashboard-head glass-panel"><div><span className="eyebrow">ط­ط³ط§ط¨ ط§ظ„ط¹ظ…ظٹظ„</span><h2>{user.name}</h2><p>{user.email}</p></div></div><div className="glass-panel dashboard-list"><h3>ظ…ط´طھط±ظٹط§طھظٹ ظˆط§ظ„طھظ†ط²ظٹظ„ط§طھ</h3>{error ? <p>{error}</p> : items.length ? items.map((item) => <div className="dashboard-item" key={item.productId}><div><h4>{item.title}</h4><small>طھظ… ط´ط±ط§ط¤ظ‡</small></div><button className="btn secondary small" onClick={() => download(item.productId)}>طھط­ظ…ظٹظ„ ط§ظ„ظ…ظ†طھط¬</button></div>) : <Empty title="ظ„ط§ طھظˆط¬ط¯ ظ…ط´طھط±ظٹط§طھ" text="ط³طھط¸ظ‡ط± ظ…ظ†طھط¬ط§طھظƒ ظ‡ظ†ط§ ط¨ط¹ط¯ ط§ظ„ط´ط±ط§ط،." />}</div></section>; }
function Admin({ user }: { user: User | null }) { const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<Array<{ _id: string; total: number; status: string }>>([]); const [form, setForm] = useState({ title: '', category: '', price: '', imageUrl: '', description: '', fileUrl: '' }); const [message, setMessage] = useState(''); const load = async () => { try { const [nextProducts, nextOrders] = await Promise.all([api<Product[]>('/products'), api<typeof orders>('/admin/orders')]); setProducts(nextProducts); setOrders(nextOrders); } catch (e) { setMessage((e as Error).message); } }; useEffect(() => { if (user?.role === 'admin') void load(); }, [user]); if (!user || user.role !== 'admin') return <AuthRequired />; const add = async (e: FormEvent) => { e.preventDefault(); try { await api('/products', { method: 'POST', body: JSON.stringify({ ...form, price: Number(form.price), shortDescription: form.description }) }); setForm({ title: '', category: '', price: '', imageUrl: '', description: '', fileUrl: '' }); setMessage('طھظ…طھ ط¥ط¶ط§ظپط© ط§ظ„ظ…ظ†طھط¬'); await load(); } catch (err) { setMessage((err as Error).message); } }; const remove = async (id: string) => { await api(`/admin/products/${id}`, { method: 'DELETE' }); await load(); }; return <section className="section-block dashboard-shell"><div className="section-heading"><div><span className="eyebrow">طµظ„ط§ط­ظٹط§طھ ط§ظ„ظ…ط¯ظٹط±</span><h2>ط¥ط¯ط§ط±ط© ط§ظ„ظ…طھط¬ط±</h2></div></div><form className="glass-panel checkout-form" onSubmit={add}><div className="field-grid">{Object.entries(form).map(([key, value]) => <label key={key}>{({ title: 'ط§ط³ظ… ط§ظ„ظ…ظ†طھط¬', category: 'ط§ظ„طھطµظ†ظٹظپ', price: 'ط§ظ„ط³ط¹ط±', imageUrl: 'ط±ط§ط¨ط· ط§ظ„طµظˆط±ط©', description: 'ط§ظ„ظˆطµظپ', fileUrl: 'ط±ط§ط¨ط· ط§ظ„ظ…ظ„ظپ ط§ظ„ظ…ط­ظ…ظٹ' } as Record<string, string>)[key]}<input required={key !== 'fileUrl'} value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}</div><button className="btn primary">ط¥ط¶ط§ظپط© ط§ظ„ظ…ظ†طھط¬</button>{message ? <p>{message}</p> : null}</form><div className="glass-panel dashboard-list"><h3>ط§ظ„ظ…ظ†طھط¬ط§طھ ط§ظ„ط­ط§ظ„ظٹط©</h3>{products.map((p) => <div className="dashboard-item" key={p._id}><div><h4>{p.title}</h4><small>{price(p.price)}</small></div><button className="text-btn" onClick={() => void remove(p._id)}>طھط¹ط·ظٹظ„</button></div>)}</div><div className="glass-panel dashboard-list"><h3>ط¢ط®ط± ط§ظ„ط·ظ„ط¨ط§طھ</h3>{orders.map((order) => <div className="dashboard-item" key={order._id}><div><h4>ط·ظ„ط¨ #{order._id.slice(-6)}</h4><small>{order.status}</small></div><strong>{price(order.total)}</strong></div>)}</div></section>; }
function AuthRequired() { return <Empty title="ط³ط¬ظ‘ظ„ ط§ظ„ط¯ط®ظˆظ„ ط£ظˆظ„ظ‹ط§" text="طھط­طھط§ط¬ ط¥ظ„ظ‰ ط­ط³ط§ط¨ ظ„ظ„ظˆطµظˆظ„." action={<Link className="btn primary" to="/auth">طھط³ط¬ظٹظ„ ط§ظ„ط¯ط®ظˆظ„</Link>} />; }
function Loading() { return <div className="loading-grid">{[1, 2, 3].map((n) => <div className="skeleton-card glass-panel" key={n} />)}</div>; }
function Empty({ title, text, action }: { title: string; text: string; action?: ReactNode }) { return <div className="empty-panel glass-panel"><h3>{title}</h3><p>{text}</p>{action}</div>; }

export default App;

